steps:
    # deploy background on app engine
    - id: 'background deploy'
      name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'dispatch.yaml', 'cron.yaml', 'app-${_ENV}-background.yaml', '--version=production1']
      waitFor: ['-']

    # Install pip dependencies
    - id: 'pip-install'
      name: 'python:3.7'
      entrypoint: python3
      waitFor: ['-']
      args: ['-m', 'pip', 'install', '-t', './venv', '-r', 'requirements.txt']


    # Launch Cloud SQL proxy and keep it open
    # until the db migration step is finished
    # https://cloud.google.com/sql/docs/postgres/sql-proxy
    - id: 'proxy'
      name: 'gcr.io/cloudsql-docker/gce-proxy'
      entrypoint: sh
      args:
          - '-c'
          - '/cloud_sql_proxy -dir=/cloudsql -instances=${_INSTANCE} & while [ ! -f /cloudsql/stop ]; do sleep 2; done'
      waitFor: ['-']
      timeout: '1200s'
      volumes:
          - name: db
            path: /cloudsql


    # Migrate database schema
    - id: 'migrate database'
      name: 'python:3.7'
      entrypoint: sh
      args:
          - '-c'
          - 'python3 ./manage.py migrate --noinput && touch /cloudsql/stop'
      env:
          - 'PYTHONPATH=./venv'
          - 'DJANGO_SETTINGS_MODULE=sportcrm.settings.gcp_${_ENV}'
      volumes:
          - name: db
            path: /cloudsql
      waitFor: ['pip-install']

    # Make messages
    - id: 'make-messages'
      name: 'python:3.7'
      entrypoint: python3
      args: ['./manage.py', 'makemessages', '--noinput']
      env:
          - 'PYTHONPATH=./venv'
          - 'DJANGO_SETTINGS_MODULE=sportcrm.settings.gcp_${_ENV}'
      waitFor: ['pip-install', 'background deploy']

    # Collect static
    - id: 'collect-static'
      name: 'python:3.7'
      entrypoint: python3
      args: ['./manage.py', 'collectstatic', '--noinput']
      env:
          - 'PYTHONPATH=./venv'
          - 'DJANGO_SETTINGS_MODULE=sportcrm.settings.gcp_${_ENV}'
      waitFor: ['pip-install', 'background deploy']


    # deploy on app engine
    - id: 'deploy'
      name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'app-${_ENV}.yaml', '--version=production1']
      waitFor: ['collect-static']

timeout: "1600s"
