# Generated by Django 2.1.7 on 2019-03-18 18:31

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0020_fix_merge_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Код сообщения')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена ли отправка сообщения')),
                ('template', models.TextField(max_length=10000, verbose_name='Шаблон сообщения')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='messagemeta',
            unique_together={('id', 'company', 'uuid')},
        ),
    ]
