# Generated by Django 2.1.7 on 2019-03-17 07:29

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0020_fix_merge_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIgnorance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, verbose_name='Тип сообщения')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена ли отправка сообщения')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='messageignorance',
            unique_together={('id', 'company', 'type')},
        ),
    ]
