# Generated by Django 2.1.7 on 2019-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_fix_merge_action'),
        ('bot', '0001_add_message_meta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagemeta',
            unique_together={('company', 'uuid')},
        ),
    ]
