# Generated by Django 2.1.5 on 2019-01-11 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(default=None, max_length=50, null=True)),
                ('email_adress', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('visit_limit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='client_subscriptions',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients'),
        ),
        migrations.AddField(
            model_name='client_subscriptions',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.subscriptions'),
        ),
    ]
