# Generated by Django 2.1.5 on 2019-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190113_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionstype',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='visit_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
