# Generated by Django 2.1.5 on 2019-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190120_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(null=True, verbose_name='id ученика в ВК'),
        ),
    ]
