# Generated by Django 2.1.5 on 2019-01-20 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190120_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscriptions',
            name='price',
            field=models.FloatField(default=100, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='visits_left',
            field=models.PositiveIntegerField(default=8, verbose_name='Остаток посещений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionstype',
            name='event_class',
            field=models.ManyToManyField(to='crm.EventClass'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Продолжительность (дни)'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='visit_limit',
            field=models.PositiveIntegerField(verbose_name='Количество посещений'),
        ),
    ]
