# Generated by Django 2.1.5 on 2019-01-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190120_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.SubscriptionsType', verbose_name='Тип Абонемента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.EventClass', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Location', verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назвение'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='event_class',
            field=models.ManyToManyField(to='crm.EventClass', verbose_name='Допустимые тренировки'),
        ),
    ]
