# Generated by Django 2.1.5 on 2019-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190121_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата с'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата по'),
        ),
    ]
