# Generated by Django 2.1.5 on 2019-01-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20190124_1947'),
        ('crm', '0014_auto_20190125_1910'),
    ]

    operations = [
    ]
