# Generated by Django 2.1.5 on 2019-01-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20190129_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EventClass'),
        ),
    ]
