# Generated by Django 2.2a1 on 2019-02-10 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20190202_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoftheweekclass',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время окнчания тренировки'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала тренировки'),
        ),
    ]
