# Generated by Django 2.1.7 on 2019-03-31 11:17

import crm.models
import datetime
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.utils
import phonenumber_field.modelfields
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# crm.migrations.0001_initial
# crm.migrations.0009_auto_20190304_0037
# crm.migrations.0027_fill_visits_on_by_time

def create_admin_company(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Company = apps.get_model("crm", "Company")
    Company.objects.create(
        name=crm.models.INTERNAL_COMPANY,
        display_name=crm.models.INTERNAL_COMPANY
    )


class Migration(migrations.Migration):
    replaces = [('crm', '0001_initial'), ('crm', '0002_add_coach_phone'), ('crm', '0003_safe_delete_models'),
                ('crm', '0004_event_cancellation'), ('crm', '0004_add_subscription_to_attendance'),
                ('crm', '0005_merge_20190228_2311'), ('crm', '0006_client_subscription_date_only'),
                ('crm', '0007_add_canceled_meta'), ('crm', '0008_client_qr_code'), ('crm', '0009_auto_20190304_0037'),
                ('crm', '0010_auto_20190304_0037'), ('crm', '0008_auto_20190304_2103'),
                ('crm', '0011_merge_20190305_0133'), ('crm', '0012_add_phone_to_manager_and_switch_coach'),
                ('crm', '0012_add_extended_from'), ('crm', '0013_merge_20190308_2318'), ('crm', '0014_event_is_closed'),
                ('crm', '0012_auto_20190312_1106'), ('crm', '0015_merge_20190312_2230'),
                ('crm', '0008_subscriptionstype_one_time'), ('crm', '0016_merge_20190313_2315'),
                ('crm', '0017_add_company_active_date'), ('crm', '0018_fix_default_datetime'),
                ('crm', '0017_auto_20190314_1449'), ('crm', '0019_merge_20190315_2315'),
                ('crm', '0020_fix_merge_action'), ('crm', '0008_auto_20190314_2033'),
                ('crm', '0015_merge_20190314_2048'), ('crm', '0021_merge_20190322_1911'),
                ('crm', '0022_auto_20190322_1911'), ('crm', '0021_merge_20190320_2329'),
                ('crm', '0023_merge_20190322_2238'), ('crm', '0021_merge_20190322_1456'),
                ('crm', '0022_auto_20190322_2053'), ('crm', '0024_merge_20190322_2306'),
                ('crm', '0025_remove_obsolete_field'), ('crm', '0026_add_visits_on_by_time'),
                ('crm', '0027_fill_visits_on_by_time'), ('crm', '0028_make_visits_non_null')]

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', crm.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email_address', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('vk_user_id', models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(null=True)),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('visits_left', models.PositiveIntegerField(verbose_name='Остаток посещений')),
                ('client', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик')),
            ],
            options={
                'ordering': ['purchase_date'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfTheWeekClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала тренировки')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время окнчания тренировки')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('coach', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Coach', verbose_name='Тренер')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExtensionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_extended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продления')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина продления')),
                ('added_visits', models.PositiveIntegerField(verbose_name='Добавлено посещений')),
                ('client_subscription', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент клиента')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            options={
                'ordering': ['date_extended'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=1000, verbose_name='Адрес')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('duration_type', models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default=('day', 'День'), max_length=20, verbose_name='Временные рамки абонемента')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('rounding', models.BooleanField(default=False, verbose_name='Округление начала действия абонемента')),
                ('visit_limit', models.PositiveIntegerField(verbose_name='Количество посещений')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
                ('event_class', models.ManyToManyField(to='crm.EventClass', verbose_name='Допустимые тренировки')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='location',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Location', verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_class',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.EventClass', verbose_name='Тренировка'),
        ),
        migrations.AddField(
            model_name='dayoftheweekclass',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EventClass', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='coach',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.SubscriptionsType', verbose_name='Тип Абонемента'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Тренировка'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=crm.models.get_user_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionstype',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='eventclass',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_class', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayoftheweekclass',
            unique_together={('day', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('client', 'event')},
        ),
        migrations.RunPython(
            code=create_admin_company,
        ),
        migrations.AddField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='coach',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionstype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionstype',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='canceled_at',
            field=models.DateField(null=True, verbose_name='Дата отмены тренировки'),
        ),
        migrations.AddField(
            model_name='extensionhistory',
            name='extended_to',
            field=models.DateField(blank=True, null=True, verbose_name='Абонемент продлен до дня'),
        ),
        migrations.AddField(
            model_name='extensionhistory',
            name='related_event',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент Клиента'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='event',
            name='canceled_with_extending',
            field=models.BooleanField(default=False, verbose_name='Отмена была с продленим абонемента?'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='duration_type',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default='day', max_length=20, verbose_name='Временные рамки абонемента'),
        ),
        migrations.AddField(
            model_name='client',
            name='qr_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='QR код'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk_access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Токен группы вк'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk_confirmation_token',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Строка-подтверждение'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk_group_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ИД группы вк'),
        ),
        migrations.AddField(
            model_name='manager',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='extensionhistory',
            name='extended_from',
            field=models.DateField(blank=True, null=True, verbose_name='Абонеметы был продлен с'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Тренировка закрыта'),
        ),
        migrations.CreateModel(
            name='ClientBalanceChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_value', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс')),
                ('reason', models.TextField(blank=True, verbose_name='Причина изменения баланса')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2019, 3, 12, 11, 6, 38, 713925), verbose_name='Дата зачисления')),
                ('actual_entry_date', models.DateTimeField(default=datetime.datetime(2019, 3, 12, 11, 6, 38, 713925), verbose_name='Фактическая дата зачисления')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AddField(
            model_name='clientbalancechangehistory',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='clientbalancechangehistory',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='clientbalancechangehistory',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент Клиента'),
        ),
        migrations.RemoveField(
            model_name='clientbalancechangehistory',
            name='actual_entry_date',
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 32, 53, 427415), verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='change_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сумма изменения баланса'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 14, 48, 59, 339345), verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зачисления'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbalancechangehistory',
            unique_together={('id', 'company')},
        ),
        migrations.AddField(
            model_name='subscriptionstype',
            name='one_time',
            field=models.BooleanField(default=False, editable=False, verbose_name='Разовый абонемент'),
        ),
        migrations.AddField(
            model_name='company',
            name='active_to',
            field=models.DateField(blank=True, null=True, verbose_name='Компания активна до'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Присутствовал на мероприятии'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='signed_up',
            field=models.BooleanField(default=False, verbose_name='Записан на мероприятие'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Время окнчания тренировки'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Время начала тренировки'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='location',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Location', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='visits_on_by_time',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество визитов на момент покупки'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='visits_on_by_time',
            field=models.PositiveSmallIntegerField(verbose_name='Количество визитов на момент покупки'),
        ),
    ]
