# Generated by Django 2.1.7 on 2019-02-16 12:35

import crm.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_extended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продления')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина продления')),
                ('added_visits', models.PositiveIntegerField(verbose_name='Добавлено посещений')),
                ('client_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент клиента')),
            ],
            options={
                'ordering': ['date_extended'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', crm.models.CustomUserManager()),
            ],
        ),
    ]
