# Generated by Django 2.1.7 on 2019-02-16 10:05

import crm.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', crm.models.CustomUserManager()),
            ],
        ),
    ]
