# Generated by Django 2.1.7 on 2019-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
