# Generated by Django 2.1.5 on 2019-01-11 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('visit_limit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client_subscriptions',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='client_subscriptions',
            name='subscription_id',
        ),
        migrations.DeleteModel(
            name='client_subscriptions',
        ),
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.DeleteModel(
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Subscription'),
        ),
    ]
