# Generated by Django 2.1.7 on 2019-02-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_subsription_extension_reason'),
        ('crm', '0002_auto_20190216_1305'),
    ]

    operations = [
    ]
