# Generated by Django 2.1.7 on 2019-02-16 10:42

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Company = apps.get_model("crm", "Company")
    db_alias = schema_editor.connection.alias
    Company.objects.using(db_alias).bulk_create([
        Company(name="Default company", id=1),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190216_1540'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
