# Generated by Django 2.1.7 on 2019-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190402_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Начало тренировок'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание тренировок'),
        ),
    ]
