# Generated by Django 2.1.7 on 2019-02-16 11:37

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190216_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', crm.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
    ]
