# Generated by Django 2.1.7 on 2019-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190402_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='change_value',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма изменения баланса'),
        ),
    ]
