# Generated by Django 2.1.7 on 2019-02-26 07:32

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190226_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент Клиента'),
        ),
    ]
