# Generated by Django 2.1.7 on 2019-02-16 13:17

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190216_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayoftheweekclass',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventclass',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionstype',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.SubscriptionsType', verbose_name='Тип Абонемента'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EventClass', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.EventClass', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='coach',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='location',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Location', verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='eventclass',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionstype',
            unique_together={('id', 'company')},
        ),
    ]
