# Generated by Django 2.1.7 on 2019-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190403_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionhistory',
            name='added_visits',
            field=models.IntegerField(verbose_name='Добавлено посещений'),
        ),
    ]
