# Generated by Django 2.1.5 on 2019-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190113_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsubscriptions',
            options={'ordering': ['purchase_date']},
        ),
        migrations.AddField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
