# Generated by Django 2.1.5 on 2019-01-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190113_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsubscriptions',
            options={'ordering': ['purchase_date']},
        ),
    ]
