# Generated by Django 2.1.7 on 2019-02-28 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_merge_20190228_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
    ]
