# Generated by Django 2.1.7 on 2019-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_fix_cs_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
