# Generated by Django 2.1.7 on 2019-03-03 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_canceled_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qr_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='QR код'),
        ),
    ]
