# Generated by Django 2.1.7 on 2019-04-18 21:05

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_client_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscriptions',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Продан на тренировка'),
        ),
    ]
