# Generated by Django 2.1.7 on 2019-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_canceled_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscriptions',
            name='one_time',
            field=models.BooleanField(default=False, editable=False, verbose_name='Разовый абонемент'),
        ),
    ]
