# Generated by Django 2.1.7 on 2019-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_canceled_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qr_code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='QR код'),
        ),
    ]
