# Generated by Django 2.1.7 on 2019-04-24 11:01

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientsubscriptions_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Продан на тренировке'),
        ),
    ]
