# Generated by Django 2.1.7 on 2019-04-22 03:06

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientsubscriptions_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbalancechangehistory',
            name='changed_by',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='sold_by',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто продал'),
        ),
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='event',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Event', verbose_name='Продан на тренировке'),
        ),
    ]
