# Generated by Django 2.1.7 on 2019-03-03 19:37

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190304_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='QR код'),
        ),
    ]
