# Generated by Django 2.1.7 on 2019-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190422_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
