# Generated by Django 2.1.7 on 2019-03-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190304_0037'),
        ('crm', '0008_auto_20190304_2103'),
    ]

    operations = [
    ]
