# Generated by Django 2.1.5 on 2019-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК'),
        ),
    ]
