# Generated by Django 2.1.7 on 2019-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190430_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together=set(),
        ),
    ]
