# Generated by Django 2.1.4 on 2019-01-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190116_2159'),
        ('crm', '0011_auto_20190121_0011'),
    ]

    operations = [
    ]
