# Generated by Django 2.1.7 on 2019-03-09 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.utils


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_merge_20190305_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, default=0, verbose_name='Баланс')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина изменения баланса')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2019, 3, 9, 18, 21, 13, 137316), verbose_name='Дата зачисления')),
                ('actual_entry_date', models.DateTimeField(default=datetime.datetime(2019, 3, 9, 18, 21, 13, 137316), verbose_name='Фактическая дата зачисления')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='company',
            field=models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='subscription',
            field=django_multitenant.fields.TenantForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.ClientSubscriptions', verbose_name='Абонемент Клиента'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbalance',
            unique_together={('id', 'company')},
        ),
    ]
