# Generated by Django 2.1.7 on 2019-03-05 14:44

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_merge_20190305_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
                ('reason', models.TextField(verbose_name='Причина изменения баланса')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='entry_date',
            field=models.DateField(default=datetime.date(2019, 3, 6), verbose_name='Дата зачисления'),
        ),
    ]
