# Generated by Django 2.1.7 on 2019-07-17 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.utils


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190508_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_event', models.BooleanField(default=True, verbose_name='Разовая тренировка?')),
                ('from_date', models.DateField(help_text='Если тренировка разовая - то это дата самой тренировки', verbose_name='Дата начала тренировки')),
                ('to_date', models.DateField(help_text='Если тренировка разовая - данные поля игнорируются', null=True, verbose_name='Дата окончания тренировки')),
                ('day_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Детальная информация по времени занятия и дня, в виде словаря')),
                ('company', models.ForeignKey(default=django_multitenant.utils.get_current_tenant, on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
                ('event_class', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EventClass', verbose_name='Мероприятие')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='event_class_section',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.EventClassSection', verbose_name='Период событий'),
        ),
        migrations.AlterUniqueTogether(
            name='eventclasssection',
            unique_together={('id', 'company')},
        ),
    ]
