# Generated by Django 2.1.5 on 2019-01-25 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_merge_20190121_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsubscriptions',
            options={'ordering': ['purchase_date']},
        ),
        migrations.AddField(
            model_name='clientsubscriptions',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует до'),
        ),
    ]
