# Generated by Django 2.1.7 on 2019-03-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_extended_from'),
        ('crm', '0012_add_phone_to_manager_and_switch_coach'),
    ]

    operations = [
    ]
