# Generated by Django 2.1.7 on 2019-08-20 19:13

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20190718_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionstype',
            name='no_visit_limit',
            field=models.BooleanField(default=False, editable=False, verbose_name='Безлимит'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='visit_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Количество посещений'),
        ),
    ]
