# Generated by Django 2.1.5 on 2019-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20190125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
