# Generated by Django 2.1.7 on 2019-03-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_subscriptionstype_one_time'),
        ('crm', '0015_merge_20190312_2230'),
    ]

    operations = [
    ]
