# Generated by Django 2.1.7 on 2019-03-14 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_merge_20190313_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_to',
            field=models.DateField(blank=True, null=True, verbose_name='Компания активна до'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='actual_entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 32, 53, 427440), verbose_name='Фактическая дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 32, 53, 427415), verbose_name='Дата зачисления'),
        ),
    ]
