# Generated by Django 2.1.5 on 2019-01-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190127_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
