# Generated by Django 2.1.5 on 2019-01-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_client_balance'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM crm_attendance;"),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('client', 'event')},
        ),
    ]
