# Generated by Django 2.1.7 on 2019-03-14 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_add_company_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='actual_entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Фактическая дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зачисления'),
        ),
    ]
