# Generated by Django 2.1.7 on 2019-03-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20190314_1449'),
        ('crm', '0018_fix_default_datetime'),
    ]

    operations = [
    ]
