# Generated by Django 2.1.5 on 2019-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20190127_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_class', 'date')},
        ),
    ]
