# Generated by Django 2.1.5 on 2019-01-29 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_manial_20190127_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeekClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('start_time', models.DateTimeField(verbose_name='Время начала тренировки')),
                ('duration', models.IntegerField(default=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.EventClass')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dayoftheweekclass',
            unique_together={('day', 'event')},
        ),
    ]
