# Generated by Django 2.1.7 on 2019-03-22 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_merge_20190322_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Время окнчания тренировки'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Время начала тренировки'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='location',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Location', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
