# Generated by Django 2.1.7 on 2019-03-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20190322_1911'),
        ('crm', '0021_merge_20190320_2329'),
    ]

    operations = [
    ]
