# Generated by Django 2.1.5 on 2019-02-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20190202_1339'),
        ('crm', '0020_auto_20190129_1908'),
    ]

    operations = [
    ]
