# Generated by Django 2.1.7 on 2019-03-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_merge_20190322_2238'),
        ('crm', '0022_auto_20190322_2053'),
    ]

    operations = [
    ]
