# Generated by Django 2.1.5 on 2019-02-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190129_2122'),
        ('crm', '0023_auto_20190202_1339'),
    ]

    operations = [
    ]
