# Generated by Django 2.2a1 on 2019-02-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20190210_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoftheweekclass',
            name='duration',
        ),
    ]
