# Generated by Django 2.1.5 on 2019-02-05 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_merge_20190205_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='day',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Продолжительность (мин.)'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EventClass', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='dayoftheweekclass',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала тренировки'),
        ),
    ]
