# Generated by Django 2.1.7 on 2019-03-25 14:22

from django.db import migrations


def fill_visits_on_by_time(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ClientSubscriptions = apps.get_model("crm", "ClientSubscriptions")
    for cs in ClientSubscriptions.objects.all():
        cs.visits_on_by_time = cs.visits_left
        cs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_add_visits_on_by_time'),
    ]

    operations = [
        migrations.RunPython(fill_visits_on_by_time),
    ]
