# Generated by Django 2.1.7 on 2019-02-28 10:22

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_safe_delete_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='canceled_at',
            field=models.DateField(null=True, verbose_name='Дата отмены тренировки'),
        ),
        migrations.AddField(
            model_name='extensionhistory',
            name='extended_to',
            field=models.DateField(blank=True, null=True, verbose_name='Абонемент продлен до дня'),
        ),
        migrations.AddField(
            model_name='extensionhistory',
            name='related_event',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Event'),
        ),
    ]
