# Generated by Django 2.1.7 on 2019-02-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_subscription_to_attendance'),
        ('crm', '0004_event_cancellation'),
    ]

    operations = [
    ]
