# Generated by Django 2.1.7 on 2019-03-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_client_subscription_date_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled_with_extending',
            field=models.BooleanField(default=False, verbose_name='Отмена была с продленим абонемента?'),
        ),
        migrations.AlterField(
            model_name='subscriptionstype',
            name='duration_type',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default='day', max_length=20, verbose_name='Временные рамки абонемента'),
        ),
    ]
