# Generated by Django 2.1.7 on 2019-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_canceled_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Присутствовал на мероприятии'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='signed_up',
            field=models.BooleanField(default=False, verbose_name='Записан на мероприятие'),
        ),
    ]
