# Generated by Django 2.1.7 on 2019-03-03 19:37

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    my_model = apps.get_model('crm', 'client')
    for row in my_model.objects.all():
        row.qr_code = uuid.uuid4()
        row.save(update_fields=['qr_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_client_qr_code'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]

