# Generated by Django 2.1.7 on 2019-03-07 19:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_merge_20190305_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
    ]
