# Generated by Django 2.1.7 on 2019-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_merge_20190305_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionhistory',
            name='extended_from',
            field=models.DateField(blank=True, null=True, verbose_name='Абонеметы был продлен с'),
        ),
    ]
