# Generated by Django 2.1.7 on 2019-03-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_event_is_closed'),
        ('crm', '0012_auto_20190312_1106'),
    ]

    operations = [
    ]
