# Generated by Django 2.1.7 on 2019-03-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_event_is_closed'),
        ('crm', '0008_auto_20190314_2033'),
    ]

    operations = [
    ]
