# Generated by Django 2.1.7 on 2019-03-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_merge_20190313_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vk_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id ученика в ВК'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='actual_entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 14, 48, 59, 339846), verbose_name='Фактическая дата зачисления'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='change_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сумма изменения баланса'),
        ),
        migrations.AlterField(
            model_name='clientbalancechangehistory',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 14, 48, 59, 339345), verbose_name='Дата зачисления'),
        ),
    ]
