# Generated by Django 2.1.7 on 2019-03-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_fix_merge_action'),
        ('crm', '0015_merge_20190314_2048'),
    ]

    operations = [
    ]
