# Generated by Django 2.1.7 on 2019-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_remove_obsolete_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscriptions',
            name='visits_on_by_time',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество визитов на момент покупки'),
        ),
    ]
